namespace ReestrParse.Application.Monitoring;

public static class ParserTelemetryExtensions
{
    public static void Info(
        this IParserTelemetry telemetry,
        ParserPipelineStage stage,
        string operation,
        string message,
        TimeSpan? duration = null,
        int? workerId = null,
        int? page = null,
        int? totalPages = null,
        int? itemIndex = null,
        int? totalItems = null,
        int? succeeded = null,
        int? failed = null,
        int? partial = null,
        string? organizationName = null,
        string? inn = null,
        string? code = null,
        string? dataSource = null)
        => telemetry.Publish(new ParserTelemetryEvent(
            DateTimeOffset.Now,
            ParserLogLevel.Info,
            stage,
            operation,
            message,
            duration,
            workerId,
            page,
            totalPages,
            itemIndex,
            totalItems,
            succeeded,
            failed,
            partial,
            organizationName,
            inn,
            null,
            code,
            dataSource));

    public static void Success(
        this IParserTelemetry telemetry,
        ParserPipelineStage stage,
        string operation,
        string message,
        TimeSpan? duration = null,
        int? workerId = null,
        int? page = null,
        int? totalPages = null,
        int? itemIndex = null,
        int? totalItems = null,
        int? succeeded = null,
        int? failed = null,
        int? partial = null,
        string? organizationName = null,
        string? inn = null,
        string? code = null,
        string? dataSource = null)
        => telemetry.Publish(new ParserTelemetryEvent(
            DateTimeOffset.Now,
            ParserLogLevel.Success,
            stage,
            operation,
            message,
            duration,
            workerId,
            page,
            totalPages,
            itemIndex,
            totalItems,
            succeeded,
            failed,
            partial,
            organizationName,
            inn,
            null,
            code,
            dataSource));

    public static void Warning(
        this IParserTelemetry telemetry,
        ParserPipelineStage stage,
        string operation,
        string message,
        TimeSpan? duration = null,
        int? workerId = null,
        int? page = null,
        int? totalPages = null,
        int? itemIndex = null,
        int? totalItems = null,
        int? succeeded = null,
        int? failed = null,
        int? partial = null,
        string? organizationName = null,
        string? inn = null,
        string? error = null,
        string? code = null,
        string? dataSource = null)
        => telemetry.Publish(new ParserTelemetryEvent(
            DateTimeOffset.Now,
            ParserLogLevel.Warning,
            stage,
            operation,
            message,
            duration,
            workerId,
            page,
            totalPages,
            itemIndex,
            totalItems,
            succeeded,
            failed,
            partial,
            organizationName,
            inn,
            error,
            code,
            dataSource));

    public static void Error(
        this IParserTelemetry telemetry,
        ParserPipelineStage stage,
        string operation,
        string message,
        Exception? exception = null,
        TimeSpan? duration = null,
        int? workerId = null,
        int? page = null,
        int? totalPages = null,
        int? itemIndex = null,
        int? totalItems = null,
        int? succeeded = null,
        int? failed = null,
        int? partial = null,
        string? organizationName = null,
        string? inn = null,
        string? error = null,
        string? code = null,
        string? dataSource = null)
        => telemetry.Publish(new ParserTelemetryEvent(
            DateTimeOffset.Now,
            ParserLogLevel.Error,
            stage,
            operation,
            message,
            duration,
            workerId,
            page,
            totalPages,
            itemIndex,
            totalItems,
            succeeded,
            failed,
            partial,
            organizationName,
            inn,
            error ?? exception?.Message,
            code,
            dataSource));
}
